name: CI

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    # run CI every day even if no PRs/merges occur
    - cron: "0 12 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:22.11
      - name: mttn
        run: nix build .#mttn
      - name: tiny86
        run: nix build .#tiny86
